### ISSUE TITLE
dependencies problem

### ISSUE THREAD

**Issue by ronneyismaelcodebakerz** [ivanderbu2/angular-redux#1]
ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/option/optgroup.d.ts (8,22): Class 'MdOptgroup' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdOptgroup'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/option/optgroup.d.ts (8,41): Type '(new (...args: any[]) => CanDisable) & typeof MdOptgroupBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/overlay/scroll/scrollable.d.ts (8,49): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/overlay/scroll/scroll-dispatcher.d.ts (17,42): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/overlay/overlay-directives.d.ts (8,78): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/ripple/ripple-renderer.d.ts (13,46): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/ripple/ripple-renderer.d.ts (15,47): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/ripple/ripple.d.ts (8,67): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/a11y/live-announcer.d.ts (8,10): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/line/line.d.ts (8,10): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/style/focus-origin-monitor.d.ts (8,65): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/style/focus-origin-monitor.d.ts (12,38): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (8,31): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (9,33): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (10,34): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (11,33): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (12,30): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (13,32): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (14,27): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (15,26): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (16,28): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (17,28): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (18,26): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (19,29): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (20,32): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (21,29): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/compatibility/compatibility.d.ts (8,22): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/common-behaviors/color.d.ts (9,22): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/selection/pseudo-checkbox/pseudo-checkbox.d.ts (8,22): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/selection/pseudo-checkbox/pseudo-checkbox.d.ts (28,22): Class 'MdPseudoCheckbox' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdPseudoCheckbox'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/selection/pseudo-checkbox/pseudo-checkbox.d.ts (28,47): Type '(new (...args: any[]) => CanColor) & typeof MdPseudoCheckboxBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/common-behaviors/common-module.d.ts (8,10): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/datetime/date-formats.d.ts (8,10): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/core/placeholder/placeholder-options.d.ts (8,10): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/input/input-container.d.ts (8,120): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/autocomplete/autocomplete-trigger.d.ts (26,49): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/autocomplete/autocomplete-trigger.d.ts (28,48): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button/button.d.ts (8,33): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button/button.d.ts (54,22): Class 'MdButton' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdButton'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button/button.d.ts (54,22): Class 'MdButton' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdButton'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button/button.d.ts (54,39): Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdButtonBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts (8,22): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts (31,22): Class 'MdButtonToggleGroup' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdButtonToggleGroup'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts (31,50): Type '(new (...args: any[]) => CanDisable) & typeof MdButtonToggleGroupBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts (90,22): Class 'MdButtonToggleGroupMultiple' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdButtonToggleGroupMultiple'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts (90,58): Type '(new (...args: any[]) => CanDisable) & typeof MdButtonToggleGroupBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/chips/chip.d.ts (8,47): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/chips/chip.d.ts (30,22): Class 'MdChip' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdChip'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/chips/chip.d.ts (30,22): Class 'MdChip' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdChip'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/chips/chip.d.ts (30,37): Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdChipBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/checkbox/checkbox.d.ts (8,81): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/checkbox/checkbox.d.ts (54,22): Class 'MdCheckbox' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdCheckbox'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/checkbox/checkbox.d.ts (54,22): Class 'MdCheckbox' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdCheckbox'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/checkbox/checkbox.d.ts (54,41): Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdCheckboxBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/dialog/dialog-container.d.ts (9,32): Cannot find module '@angular/animations'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/datepicker/datepicker-input.d.ts (8,65): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/datepicker/datepicker-input.d.ts (10,49): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/forms/index"' has no exported member 'ValidationErrors'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/dialog/dialog-injector.d.ts (8,20): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/expansion/expansion-panel.d.ts (7,55): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/grid-list/grid-tile.d.ts (8,10): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/grid-list/grid-list.d.ts (8,50): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/icon/icon.d.ts (8,41): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/icon/icon.d.ts (50,22): Class 'MdIcon' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdIcon'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/icon/icon.d.ts (50,37): Type '(new (...args: any[]) => CanColor) & typeof MdIconBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/list/list.d.ts (8,51): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/menu/menu-item.d.ts (18,22): Class 'MdMenuItem' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdMenuItem'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/menu/menu-item.d.ts (18,41): Type '(new (...args: any[]) => CanDisable) & typeof MdMenuItemBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/menu/menu-animations.d.ts (8,42): Cannot find module '@angular/animations'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/progress-spinner/progress-spinner.d.ts (8,41): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/progress-spinner/progress-spinner.d.ts (11,52): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/progress-spinner/progress-spinner.d.ts (28,22): Class 'MdProgressSpinner' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdProgressSpinner'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/progress-spinner/progress-spinner.d.ts (28,48): Type '(new (...args: any[]) => CanColor) & typeof MdProgressSpinnerBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/radio/radio.d.ts (8,59): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/radio/radio.d.ts (32,43): Type '(new (...args: any[]) => CanDisable) & typeof MdRadioGroupBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/radio/radio.d.ts (131,22): Class 'MdRadioButton' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdRadioButton'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/radio/radio.d.ts (131,44): Type '(new (...args: any[]) => CanColor) & typeof MdRadioButtonBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (8,76): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (29,41): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (31,46): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (35,44): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (42,45): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (59,45): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (64,52): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (77,22): Class 'MdSelect' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdSelect'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (77,22): Class 'MdSelect' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdSelect'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select.d.ts (77,39): Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdSelectBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/select/select-animations.d.ts (8,42): Cannot find module '@angular/animations'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/sidenav/sidenav.d.ts (8,65): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/slider/slider.d.ts (8,47): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/slider/slider.d.ts (33,22): Class 'MdSlider' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdSlider'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/slider/slider.d.ts (33,39): Type '(new (...args: any[]) => CanDisable) & typeof MdSliderBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/slide-toggle/slide-toggle.d.ts (8,84): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/slide-toggle/slide-toggle.d.ts (25,22): Class 'MdSlideToggle' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdSlideToggle'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/slide-toggle/slide-toggle.d.ts (25,22): Class 'MdSlideToggle' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdSlideToggle'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/slide-toggle/slide-toggle.d.ts (25,44): Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdSlideToggleB...' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/snack-bar/snack-bar-container.d.ts (8,43): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/snack-bar/snack-bar-container.d.ts (9,32): Cannot find module '@angular/animations'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/snack-bar/snack-bar-container.d.ts (14,37): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/snack-bar/snack-bar-container.d.ts (15,37): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tabs/tab.d.ts (15,22): Class 'MdTab' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdTab'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tabs/tab.d.ts (15,36): Type '(new (...args: any[]) => CanDisable) & typeof MdTabBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tabs/tab-group.d.ts (8,47): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tabs/ink-bar.d.ts (8,10): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tabs/tab-body.d.ts (9,32): Cannot find module '@angular/animations'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tabs/tab-label-wrapper.d.ts (17,22): Class 'MdTabLabelWrapper' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdTabLabelWrapper'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tabs/tab-label-wrapper.d.ts (17,48): Type '(new (...args: any[]) => CanDisable) & typeof MdTabLabelWrapperBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/toolbar/toolbar.d.ts (8,22): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/toolbar/toolbar.d.ts (18,22): Class 'MdToolbar' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MdToolbar'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/toolbar/toolbar.d.ts (18,40): Type '(new (...args: any[]) => CanColor) & typeof MdToolbarBase' is not a constructor function type.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tooltip/tooltip.d.ts (8,59): Module '"C:/BangaloreWorkspace/angular-redux/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tooltip/tooltip.d.ts (9,32): Cannot find module '@angular/animations'.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tooltip/tooltip.d.ts (18,42): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/node_modules/@angular/material/typings/tooltip/tooltip.d.ts (20,41): Initializers are not allowed in ambient contexts.

ERROR in C:/BangaloreWorkspace/angular-redux/src/app/app.module.ts (34,20): Property 'forRoot' does not exist on type 'typeof MaterialModule'.

ERROR in Error encountered resolving symbol values statically. Calling function 'MaterialModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/BangaloreWorkspace/angular-redux/src/app/app.module.ts, resolving symbol AppModule in C:/BangaloreWorkspace/angular-redux/src/app/app.module.ts

ERROR in C:/BangaloreWorkspace/angular-redux/src/app/app.module.ts (34,20): Property 'forRoot' does not exist on type 'typeof MaterialModule'.

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/animations' in 'C:\BangaloreWorkspace\angular-redux\node_modules\@angular\material\@angular'
 @ ./~/@angular/material/@angular/material.es5.js 22:0-81
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
webpack: Failed to compile.

**Comment by yuliankarapetkov** [comment]
I have the same problem as well.
